# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nikunj Khetan
email: nkhetan@bu.edu
description: > # this means to ignore newlines until "baseurl:"
  Third-year mechanical engineering student at Boston University.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://nikunjkhetan.me # the base hostname & protocol for your site, e.g. http://example.com

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: ""
    values:
      latex: no
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project

host: brentyi.com

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
